// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./baremetal/manager_factory.go

// Package mock_baremetal is a generated GoMock package.
package mock_baremetal

import (
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	v1alpha2 "sigs.k8s.io/cluster-api-provider-baremetal/api/v1alpha2"
	baremetal "sigs.k8s.io/cluster-api-provider-baremetal/baremetal"
	v1alpha20 "sigs.k8s.io/cluster-api/api/v1alpha2"
)

// MockManagerFactoryInterface is a mock of ManagerFactoryInterface interface
type MockManagerFactoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockManagerFactoryInterfaceMockRecorder
}

// MockManagerFactoryInterfaceMockRecorder is the mock recorder for MockManagerFactoryInterface
type MockManagerFactoryInterfaceMockRecorder struct {
	mock *MockManagerFactoryInterface
}

// NewMockManagerFactoryInterface creates a new mock instance
func NewMockManagerFactoryInterface(ctrl *gomock.Controller) *MockManagerFactoryInterface {
	mock := &MockManagerFactoryInterface{ctrl: ctrl}
	mock.recorder = &MockManagerFactoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManagerFactoryInterface) EXPECT() *MockManagerFactoryInterfaceMockRecorder {
	return m.recorder
}

// NewClusterManager mocks base method
func (m *MockManagerFactoryInterface) NewClusterManager(cluster *v1alpha20.Cluster, bareMetalCluster *v1alpha2.BareMetalCluster, clusterLog logr.Logger) (baremetal.ClusterManagerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClusterManager", cluster, bareMetalCluster, clusterLog)
	ret0, _ := ret[0].(baremetal.ClusterManagerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClusterManager indicates an expected call of NewClusterManager
func (mr *MockManagerFactoryInterfaceMockRecorder) NewClusterManager(cluster, bareMetalCluster, clusterLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClusterManager", reflect.TypeOf((*MockManagerFactoryInterface)(nil).NewClusterManager), cluster, bareMetalCluster, clusterLog)
}

// NewMachineManager mocks base method
func (m *MockManagerFactoryInterface) NewMachineManager(arg0 *v1alpha20.Cluster, arg1 *v1alpha2.BareMetalCluster, arg2 *v1alpha20.Machine, arg3 *v1alpha2.BareMetalMachine, arg4 logr.Logger) (baremetal.MachineManagerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMachineManager", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(baremetal.MachineManagerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMachineManager indicates an expected call of NewMachineManager
func (mr *MockManagerFactoryInterfaceMockRecorder) NewMachineManager(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineManager", reflect.TypeOf((*MockManagerFactoryInterface)(nil).NewMachineManager), arg0, arg1, arg2, arg3, arg4)
}
