// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./baremetal/metal3remediation_manager.go

// Package baremetal_mocks is a generated GoMock package.
package baremetal_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1"
	v1beta1 "github.com/metal3-io/cluster-api-provider-metal3/api/v1beta1"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v11 "k8s.io/client-go/kubernetes/typed/core/v1"
	v1beta10 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	patch "sigs.k8s.io/cluster-api/util/deprecated/v1beta1/patch"
)

// MockRemediationManagerInterface is a mock of RemediationManagerInterface interface.
type MockRemediationManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRemediationManagerInterfaceMockRecorder
}

// MockRemediationManagerInterfaceMockRecorder is the mock recorder for MockRemediationManagerInterface.
type MockRemediationManagerInterfaceMockRecorder struct {
	mock *MockRemediationManagerInterface
}

// NewMockRemediationManagerInterface creates a new mock instance.
func NewMockRemediationManagerInterface(ctrl *gomock.Controller) *MockRemediationManagerInterface {
	mock := &MockRemediationManagerInterface{ctrl: ctrl}
	mock.recorder = &MockRemediationManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemediationManagerInterface) EXPECT() *MockRemediationManagerInterfaceMockRecorder {
	return m.recorder
}

// AddOutOfServiceTaint mocks base method.
func (m *MockRemediationManagerInterface) AddOutOfServiceTaint(ctx context.Context, clusterClient v11.CoreV1Interface, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOutOfServiceTaint", ctx, clusterClient, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOutOfServiceTaint indicates an expected call of AddOutOfServiceTaint.
func (mr *MockRemediationManagerInterfaceMockRecorder) AddOutOfServiceTaint(ctx, clusterClient, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOutOfServiceTaint", reflect.TypeOf((*MockRemediationManagerInterface)(nil).AddOutOfServiceTaint), ctx, clusterClient, node)
}

// DeleteNode mocks base method.
func (m *MockRemediationManagerInterface) DeleteNode(ctx context.Context, clusterClient v11.CoreV1Interface, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, clusterClient, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockRemediationManagerInterfaceMockRecorder) DeleteNode(ctx, clusterClient, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockRemediationManagerInterface)(nil).DeleteNode), ctx, clusterClient, node)
}

// GetCapiMachine mocks base method.
func (m *MockRemediationManagerInterface) GetCapiMachine(ctx context.Context) (*v1beta10.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapiMachine", ctx)
	ret0, _ := ret[0].(*v1beta10.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCapiMachine indicates an expected call of GetCapiMachine.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetCapiMachine(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapiMachine", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetCapiMachine), ctx)
}

// GetClusterClient mocks base method.
func (m *MockRemediationManagerInterface) GetClusterClient(ctx context.Context) (v11.CoreV1Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterClient", ctx)
	ret0, _ := ret[0].(v11.CoreV1Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterClient indicates an expected call of GetClusterClient.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetClusterClient(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterClient", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetClusterClient), ctx)
}

// GetLastRemediatedTime mocks base method.
func (m *MockRemediationManagerInterface) GetLastRemediatedTime() *v10.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastRemediatedTime")
	ret0, _ := ret[0].(*v10.Time)
	return ret0
}

// GetLastRemediatedTime indicates an expected call of GetLastRemediatedTime.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetLastRemediatedTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastRemediatedTime", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetLastRemediatedTime))
}

// GetNode mocks base method.
func (m *MockRemediationManagerInterface) GetNode(ctx context.Context, clusterClient v11.CoreV1Interface) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, clusterClient)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetNode(ctx, clusterClient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetNode), ctx, clusterClient)
}

// GetNodeBackupAnnotations mocks base method.
func (m *MockRemediationManagerInterface) GetNodeBackupAnnotations() (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeBackupAnnotations")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetNodeBackupAnnotations indicates an expected call of GetNodeBackupAnnotations.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetNodeBackupAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeBackupAnnotations", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetNodeBackupAnnotations))
}

// GetRemediationPhase mocks base method.
func (m *MockRemediationManagerInterface) GetRemediationPhase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemediationPhase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRemediationPhase indicates an expected call of GetRemediationPhase.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetRemediationPhase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemediationPhase", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetRemediationPhase))
}

// GetRemediationType mocks base method.
func (m *MockRemediationManagerInterface) GetRemediationType() v1beta1.RemediationType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemediationType")
	ret0, _ := ret[0].(v1beta1.RemediationType)
	return ret0
}

// GetRemediationType indicates an expected call of GetRemediationType.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetRemediationType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemediationType", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetRemediationType))
}

// GetTimeout mocks base method.
func (m *MockRemediationManagerInterface) GetTimeout() *v10.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeout")
	ret0, _ := ret[0].(*v10.Duration)
	return ret0
}

// GetTimeout indicates an expected call of GetTimeout.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeout", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetTimeout))
}

// GetUnhealthyHost mocks base method.
func (m *MockRemediationManagerInterface) GetUnhealthyHost(ctx context.Context) (*v1alpha1.BareMetalHost, *patch.Helper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnhealthyHost", ctx)
	ret0, _ := ret[0].(*v1alpha1.BareMetalHost)
	ret1, _ := ret[1].(*patch.Helper)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUnhealthyHost indicates an expected call of GetUnhealthyHost.
func (mr *MockRemediationManagerInterfaceMockRecorder) GetUnhealthyHost(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnhealthyHost", reflect.TypeOf((*MockRemediationManagerInterface)(nil).GetUnhealthyHost), ctx)
}

// HasFinalizer mocks base method.
func (m *MockRemediationManagerInterface) HasFinalizer() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFinalizer")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasFinalizer indicates an expected call of HasFinalizer.
func (mr *MockRemediationManagerInterfaceMockRecorder) HasFinalizer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFinalizer", reflect.TypeOf((*MockRemediationManagerInterface)(nil).HasFinalizer))
}

// HasOutOfServiceTaint mocks base method.
func (m *MockRemediationManagerInterface) HasOutOfServiceTaint(node *v1.Node) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOutOfServiceTaint", node)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasOutOfServiceTaint indicates an expected call of HasOutOfServiceTaint.
func (mr *MockRemediationManagerInterfaceMockRecorder) HasOutOfServiceTaint(node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOutOfServiceTaint", reflect.TypeOf((*MockRemediationManagerInterface)(nil).HasOutOfServiceTaint), node)
}

// HasReachRetryLimit mocks base method.
func (m *MockRemediationManagerInterface) HasReachRetryLimit() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasReachRetryLimit")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasReachRetryLimit indicates an expected call of HasReachRetryLimit.
func (mr *MockRemediationManagerInterfaceMockRecorder) HasReachRetryLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasReachRetryLimit", reflect.TypeOf((*MockRemediationManagerInterface)(nil).HasReachRetryLimit))
}

// IncreaseRetryCount mocks base method.
func (m *MockRemediationManagerInterface) IncreaseRetryCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseRetryCount")
}

// IncreaseRetryCount indicates an expected call of IncreaseRetryCount.
func (mr *MockRemediationManagerInterfaceMockRecorder) IncreaseRetryCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseRetryCount", reflect.TypeOf((*MockRemediationManagerInterface)(nil).IncreaseRetryCount))
}

// IsNodeDrained mocks base method.
func (m *MockRemediationManagerInterface) IsNodeDrained(ctx context.Context, clusterClient v11.CoreV1Interface, node *v1.Node) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNodeDrained", ctx, clusterClient, node)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNodeDrained indicates an expected call of IsNodeDrained.
func (mr *MockRemediationManagerInterfaceMockRecorder) IsNodeDrained(ctx, clusterClient, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNodeDrained", reflect.TypeOf((*MockRemediationManagerInterface)(nil).IsNodeDrained), ctx, clusterClient, node)
}

// IsPowerOffRequested mocks base method.
func (m *MockRemediationManagerInterface) IsPowerOffRequested(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPowerOffRequested", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPowerOffRequested indicates an expected call of IsPowerOffRequested.
func (mr *MockRemediationManagerInterfaceMockRecorder) IsPowerOffRequested(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPowerOffRequested", reflect.TypeOf((*MockRemediationManagerInterface)(nil).IsPowerOffRequested), ctx)
}

// IsPoweredOn mocks base method.
func (m *MockRemediationManagerInterface) IsPoweredOn(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPoweredOn", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPoweredOn indicates an expected call of IsPoweredOn.
func (mr *MockRemediationManagerInterfaceMockRecorder) IsPoweredOn(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPoweredOn", reflect.TypeOf((*MockRemediationManagerInterface)(nil).IsPoweredOn), ctx)
}

// OnlineStatus mocks base method.
func (m *MockRemediationManagerInterface) OnlineStatus(host *v1alpha1.BareMetalHost) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnlineStatus", host)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnlineStatus indicates an expected call of OnlineStatus.
func (mr *MockRemediationManagerInterfaceMockRecorder) OnlineStatus(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnlineStatus", reflect.TypeOf((*MockRemediationManagerInterface)(nil).OnlineStatus), host)
}

// RemoveNodeBackupAnnotations mocks base method.
func (m *MockRemediationManagerInterface) RemoveNodeBackupAnnotations() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveNodeBackupAnnotations")
}

// RemoveNodeBackupAnnotations indicates an expected call of RemoveNodeBackupAnnotations.
func (mr *MockRemediationManagerInterfaceMockRecorder) RemoveNodeBackupAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNodeBackupAnnotations", reflect.TypeOf((*MockRemediationManagerInterface)(nil).RemoveNodeBackupAnnotations))
}

// RemoveOutOfServiceTaint mocks base method.
func (m *MockRemediationManagerInterface) RemoveOutOfServiceTaint(ctx context.Context, clusterClient v11.CoreV1Interface, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOutOfServiceTaint", ctx, clusterClient, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOutOfServiceTaint indicates an expected call of RemoveOutOfServiceTaint.
func (mr *MockRemediationManagerInterfaceMockRecorder) RemoveOutOfServiceTaint(ctx, clusterClient, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOutOfServiceTaint", reflect.TypeOf((*MockRemediationManagerInterface)(nil).RemoveOutOfServiceTaint), ctx, clusterClient, node)
}

// RemovePowerOffAnnotation mocks base method.
func (m *MockRemediationManagerInterface) RemovePowerOffAnnotation(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePowerOffAnnotation", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePowerOffAnnotation indicates an expected call of RemovePowerOffAnnotation.
func (mr *MockRemediationManagerInterfaceMockRecorder) RemovePowerOffAnnotation(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePowerOffAnnotation", reflect.TypeOf((*MockRemediationManagerInterface)(nil).RemovePowerOffAnnotation), ctx)
}

// RetryLimitIsSet mocks base method.
func (m *MockRemediationManagerInterface) RetryLimitIsSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryLimitIsSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RetryLimitIsSet indicates an expected call of RetryLimitIsSet.
func (mr *MockRemediationManagerInterfaceMockRecorder) RetryLimitIsSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryLimitIsSet", reflect.TypeOf((*MockRemediationManagerInterface)(nil).RetryLimitIsSet))
}

// SetFinalizer mocks base method.
func (m *MockRemediationManagerInterface) SetFinalizer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinalizer")
}

// SetFinalizer indicates an expected call of SetFinalizer.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetFinalizer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinalizer", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetFinalizer))
}

// SetLastRemediationTime mocks base method.
func (m *MockRemediationManagerInterface) SetLastRemediationTime(remediationTime *v10.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastRemediationTime", remediationTime)
}

// SetLastRemediationTime indicates an expected call of SetLastRemediationTime.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetLastRemediationTime(remediationTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastRemediationTime", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetLastRemediationTime), remediationTime)
}

// SetNodeBackupAnnotations mocks base method.
func (m *MockRemediationManagerInterface) SetNodeBackupAnnotations(annotations, labels string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNodeBackupAnnotations", annotations, labels)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetNodeBackupAnnotations indicates an expected call of SetNodeBackupAnnotations.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetNodeBackupAnnotations(annotations, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeBackupAnnotations", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetNodeBackupAnnotations), annotations, labels)
}

// SetOwnerRemediatedConditionNew mocks base method.
func (m *MockRemediationManagerInterface) SetOwnerRemediatedConditionNew(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwnerRemediatedConditionNew", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwnerRemediatedConditionNew indicates an expected call of SetOwnerRemediatedConditionNew.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetOwnerRemediatedConditionNew(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnerRemediatedConditionNew", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetOwnerRemediatedConditionNew), ctx)
}

// SetPowerOffAnnotation mocks base method.
func (m *MockRemediationManagerInterface) SetPowerOffAnnotation(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPowerOffAnnotation", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPowerOffAnnotation indicates an expected call of SetPowerOffAnnotation.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetPowerOffAnnotation(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPowerOffAnnotation", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetPowerOffAnnotation), ctx)
}

// SetRemediationPhase mocks base method.
func (m *MockRemediationManagerInterface) SetRemediationPhase(phase string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRemediationPhase", phase)
}

// SetRemediationPhase indicates an expected call of SetRemediationPhase.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetRemediationPhase(phase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemediationPhase", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetRemediationPhase), phase)
}

// SetUnhealthyAnnotation mocks base method.
func (m *MockRemediationManagerInterface) SetUnhealthyAnnotation(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnhealthyAnnotation", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnhealthyAnnotation indicates an expected call of SetUnhealthyAnnotation.
func (mr *MockRemediationManagerInterfaceMockRecorder) SetUnhealthyAnnotation(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnhealthyAnnotation", reflect.TypeOf((*MockRemediationManagerInterface)(nil).SetUnhealthyAnnotation), ctx)
}

// TimeToRemediate mocks base method.
func (m *MockRemediationManagerInterface) TimeToRemediate(timeout time.Duration) (bool, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeToRemediate", timeout)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// TimeToRemediate indicates an expected call of TimeToRemediate.
func (mr *MockRemediationManagerInterfaceMockRecorder) TimeToRemediate(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeToRemediate", reflect.TypeOf((*MockRemediationManagerInterface)(nil).TimeToRemediate), timeout)
}

// UnsetFinalizer mocks base method.
func (m *MockRemediationManagerInterface) UnsetFinalizer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsetFinalizer")
}

// UnsetFinalizer indicates an expected call of UnsetFinalizer.
func (mr *MockRemediationManagerInterfaceMockRecorder) UnsetFinalizer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetFinalizer", reflect.TypeOf((*MockRemediationManagerInterface)(nil).UnsetFinalizer))
}

// UpdateNode mocks base method.
func (m *MockRemediationManagerInterface) UpdateNode(ctx context.Context, clusterClient v11.CoreV1Interface, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", ctx, clusterClient, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MockRemediationManagerInterfaceMockRecorder) UpdateNode(ctx, clusterClient, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MockRemediationManagerInterface)(nil).UpdateNode), ctx, clusterClient, node)
}
