// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./baremetal/metal3ippool_manager.go

// Package baremetal_mocks is a generated GoMock package.
package baremetal_mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIPPoolManagerInterface is a mock of IPPoolManagerInterface interface
type MockIPPoolManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIPPoolManagerInterfaceMockRecorder
}

// MockIPPoolManagerInterfaceMockRecorder is the mock recorder for MockIPPoolManagerInterface
type MockIPPoolManagerInterfaceMockRecorder struct {
	mock *MockIPPoolManagerInterface
}

// NewMockIPPoolManagerInterface creates a new mock instance
func NewMockIPPoolManagerInterface(ctrl *gomock.Controller) *MockIPPoolManagerInterface {
	mock := &MockIPPoolManagerInterface{ctrl: ctrl}
	mock.recorder = &MockIPPoolManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPPoolManagerInterface) EXPECT() *MockIPPoolManagerInterfaceMockRecorder {
	return m.recorder
}

// SetFinalizer mocks base method
func (m *MockIPPoolManagerInterface) SetFinalizer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinalizer")
}

// SetFinalizer indicates an expected call of SetFinalizer
func (mr *MockIPPoolManagerInterfaceMockRecorder) SetFinalizer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinalizer", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).SetFinalizer))
}

// UnsetFinalizer mocks base method
func (m *MockIPPoolManagerInterface) UnsetFinalizer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsetFinalizer")
}

// UnsetFinalizer indicates an expected call of UnsetFinalizer
func (mr *MockIPPoolManagerInterfaceMockRecorder) UnsetFinalizer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetFinalizer", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).UnsetFinalizer))
}

// RecreateStatusConditionally mocks base method
func (m *MockIPPoolManagerInterface) RecreateStatusConditionally(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateStatusConditionally", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecreateStatusConditionally indicates an expected call of RecreateStatusConditionally
func (mr *MockIPPoolManagerInterfaceMockRecorder) RecreateStatusConditionally(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateStatusConditionally", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).RecreateStatusConditionally), arg0)
}

// DeleteAddresses mocks base method
func (m *MockIPPoolManagerInterface) DeleteAddresses(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddresses", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddresses indicates an expected call of DeleteAddresses
func (mr *MockIPPoolManagerInterfaceMockRecorder) DeleteAddresses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddresses", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).DeleteAddresses), arg0)
}

// CreateAddresses mocks base method
func (m *MockIPPoolManagerInterface) CreateAddresses(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddresses", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddresses indicates an expected call of CreateAddresses
func (mr *MockIPPoolManagerInterfaceMockRecorder) CreateAddresses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddresses", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).CreateAddresses), arg0)
}

// DeleteReady mocks base method
func (m *MockIPPoolManagerInterface) DeleteReady() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReady")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReady indicates an expected call of DeleteReady
func (mr *MockIPPoolManagerInterfaceMockRecorder) DeleteReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReady", reflect.TypeOf((*MockIPPoolManagerInterface)(nil).DeleteReady))
}
