version: "2"
run:
  go: "1.24"
  allow-parallel-runners: true
linters:
  default: none
  enable:
  - kubeapilinter # linter for Kube API conventions
  settings:
    custom:
      kubeapilinter:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
            - "optionalfields"
            - "nonpointerstructs"
            - "nophase"
            - "conditions"
            - "arrayofstruct"
            - "ssatags"
            - "defaults"
          lintersConfig:
            conflictingmarkers:
              conflicts:
              - name: "default_vs_required"
                sets:
                - [ "default", "kubebuilder:default" ]
                - [ "required", "kubebuilder:validation:Required", "k8s:required" ]
                description: "A field with a default value cannot be required"
            forbiddenmarkers:
              markers:
              # We don't want to do any defaulting (including OpenAPI) anymore on API fields because we prefer
              # to have a clear signal on user intent. This also allows us to easily change the default behavior if necessary.
              - identifier: "kubebuilder:default"
              - identifier: "default"
            conditions:
              isFirstField: Warn # Require conditions to be the first field in the status struct.
              usePatchStrategy: Forbid # Forbid patchStrategy markers on the Conditions field.
              useProtobuf: Forbid # We don't use protobuf, so protobuf tags are not required.
            optionalfields:
              pointers:
                preference: WhenRequired # Always | WhenRequired # Whether to always require pointers, or only when required. Defaults to `Always`.
                policy: SuggestFix # SuggestFix | Warn # The policy for pointers in optional fields. Defaults to `SuggestFix`.
              omitempty:
                policy: SuggestFix # SuggestFix | Warn | Ignore # The policy for omitempty in optional fields. Defaults to `SuggestFix`.

  exclusions:
    generated: strict
    paths:
    - zz_generated.*\.go$
    - ".*_test.go"
    - "api/v1beta1/.*"
    rules:
    ## KAL should only run on API folders.
    - path: "api/v1beta1//*"
      linters:
      - kubeapilinter

    ## Excludes for CAPM3 requiredfields
    # Metal3ClusterTemplateResource.Spec follows Cluster API contract
    # and is required, but it has a valid zero value, so we need to
    # exclude it from the requiredfields linter.
    - path: "api/v1beta2/metal3clustertemplate_types.go"
      text: "requiredfields: field Metal3ClusterTemplateResource.Spec has a valid zero value"
      linters:
      - kubeapilinter
    # Metal3MachineTemplateResource.Spec follows Cluster API contract
    # and is required, but it has a valid zero value, so we need to
    # exclude it from the requiredfields linter.
    - path: "api/v1beta2/metal3machinetemplate_types.go"
      text: "requiredfields: field Metal3MachineTemplateResource.Spec has a valid zero value"
      linters:
      - kubeapilinter
    # Metal3RemediationTemplateResource.Spec follows Cluster API contract
    # and is required, but it has a valid zero value, so we need to
    # exclude it from the requiredfields linter.
    - path: "api/v1beta2/metal3remediationtemplate_types.go"
      text: "requiredfields: field Metal3RemediationTemplateResource.Spec has a valid zero value"
      linters:
      - kubeapilinter
    # Metal3RemediationTemplateStatus.Status follows Cluster API contract
    # and is required, but it has a valid zero value, so we need to
    # exclude it from the requiredfields linter.
    - path: "api/v1beta2/metal3remediationtemplate_types.go"
      text: "requiredfields: field Metal3RemediationTemplateStatus.Status has a valid zero value"
      linters:
      - kubeapilinter
    # Type NetworkGatewayv4 has separate validation that checks that at least
    # one of the fields, FromIPPool, FromPoolRef, or FromPoolAnnotation, is set.
    # This mean that the Gateway field is never empty and we can ignore the requiredfields linter for it.
    - path: "api/v1beta2/metal3datatemplate_types.go"
      text: "requiredfields: field NetworkDataRoutev4.Gateway has a valid zero value"
      linters:
      - kubeapilinter
    # Type NetworkGatewayv6 has separate validation that checks that at least
    # one of the fields, FromIPPool, FromPoolRef, or FromPoolAnnotation, is set.
    # This mean that the Gateway field is never empty and we can ignore the requiredfields linter for it.
    - path: "api/v1beta2/metal3datatemplate_types.go"
      text: "requiredfields: field NetworkDataRoutev6.Gateway has a valid zero value"
      linters:
      - kubeapilinter

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
