---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalCluster
metadata:
  name: ${CLUSTER_NAME}
# spec:
#   cloudName: ${CLUSTER_NAME}
#   cloudsSecret:
#     name: cloud-config
spec:
  clusterName: ${CLUSTER_NAME}
  controlPlaneEndpoint:
    host: 192.168.111.249
    port: 6443
