FROM registry.hub.docker.com/library/golang:1.12

WORKDIR /usr/local/kubebuilder
COPY /hack/tools /usr/local/kubebuilder/
RUN mkdir -p /tmp/unittests && \
    mkdir -p /tmp/unittests/hack/tools && \
    ./install_kustomize.sh && \
    ./install_kubebuilder.sh && \
    cp -r /usr/local/kubebuilder/bin /tmp/unittests/hack/tools
