package e2e

import (
	"context"
	"os"
	"os/exec"
	"strings"

	. "github.com/onsi/gomega"
	"gopkg.in/yaml.v3"
)

// VMInfo holds information about a VM needed for BMH generation.
// This is loaded from the bmcs config file produced by ci-e2e.sh
// after running `vbmctl create bml`.
type VMInfo struct {
	Name            string          `yaml:"name"`
	MACAddress      string          `yaml:"bootMacAddress"`
	IPAddress       string          `yaml:"ipAddress"`
	BMCAddress      string          `yaml:"address"`
	RootDeviceHints *RootDeviceHint `yaml:"rootDeviceHints,omitempty"`
}

// RootDeviceHint mirrors the BMO RootDeviceHints for YAML parsing.
type RootDeviceHint struct {
	DeviceName string `yaml:"deviceName,omitempty"`
}

// vmInfos holds information about all created VMs (package-level for use across test files).
var vmInfos []VMInfo

// LoadVMInfos reads VM information from the YAML config file.
// The file is generated by ci-e2e.sh and follows the same format
// as BMO's bmcs-*.yaml (a YAML list of BMC entries).
func LoadVMInfos(path string) []VMInfo {
	data, err := os.ReadFile(path) // #nosec G304
	Expect(err).ToNot(HaveOccurred(), "Failed to read VM info file: %s", path)

	var infos []VMInfo
	Expect(yaml.Unmarshal(data, &infos)).To(Succeed(), "Failed to parse VM info file")
	Expect(infos).ToNot(BeEmpty(), "No VMs defined in %s", path)

	return infos
}

// PowerOffVMs forces the given VMs off using virsh destroy.
// This ensures they are in a clean power-off state before Ironic inspects them,
// avoiding the case where a VM is already on with a stale IPA that never calls back.
func PowerOffVMs(vmInfos []VMInfo) {
	for _, vm := range vmInfos {
		Logf("Forcing power off VM %s", vm.Name)
		cmd := exec.CommandContext(context.Background(), "sudo", "virsh", "destroy", vm.Name) // #nosec G204
		// Ignore errors — VM may already be off.
		output, err := cmd.CombinedOutput()
		if err != nil {
			Logf("virsh destroy %s (may already be off): %v: %s", vm.Name, err, string(output))
		}
	}
}

// ListVMsByState returns the names of libvirt VMs in the given state.
func ListVMsByState(state vmState) []string {
	var cmd *exec.Cmd
	switch state {
	case running:
		cmd = exec.CommandContext(context.Background(), "sudo", "virsh", "list", "--name", "--state-running") // #nosec G204
	case shutoff:
		cmd = exec.CommandContext(context.Background(), "sudo", "virsh", "list", "--name", "--state-shutoff") // #nosec G204
	case paused:
		cmd = exec.CommandContext(context.Background(), "sudo", "virsh", "list", "--name", "--state-paused") // #nosec G204
	case other:
		cmd = exec.CommandContext(context.Background(), "sudo", "virsh", "list", "--name", "--state-other") // #nosec G204
	default:
		return nil
	}

	result, err := cmd.Output()
	Expect(err).NotTo(HaveOccurred())

	lines := strings.Split(string(result), "\n")
	i := 0
	for _, line := range lines {
		if line != "" {
			lines[i] = line
			i++
		}
	}
	return lines[:i]
}
