// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	v1alpha4 "github.com/metal3-io/cluster-api-provider-metal3/api/v1alpha4"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	selection "k8s.io/apimachinery/pkg/selection"
	apiv1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
	v1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*APIEndpoint), b.(*v1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1alpha2_APIEndpoint(a.(*v1alpha4.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostSelector)(nil), (*v1alpha4.HostSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HostSelector_To_v1alpha4_HostSelector(a.(*HostSelector), b.(*v1alpha4.HostSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.HostSelector)(nil), (*HostSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_HostSelector_To_v1alpha2_HostSelector(a.(*v1alpha4.HostSelector), b.(*HostSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostSelectorRequirement)(nil), (*v1alpha4.HostSelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HostSelectorRequirement_To_v1alpha4_HostSelectorRequirement(a.(*HostSelectorRequirement), b.(*v1alpha4.HostSelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.HostSelectorRequirement)(nil), (*HostSelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(a.(*v1alpha4.HostSelectorRequirement), b.(*HostSelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1alpha4.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Image_To_v1alpha4_Image(a.(*Image), b.(*v1alpha4.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Image_To_v1alpha2_Image(a.(*v1alpha4.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3Cluster)(nil), (*v1alpha4.Metal3Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster(a.(*Metal3Cluster), b.(*v1alpha4.Metal3Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3Cluster)(nil), (*Metal3Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster(a.(*v1alpha4.Metal3Cluster), b.(*Metal3Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3ClusterList)(nil), (*v1alpha4.Metal3ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3ClusterList_To_v1alpha4_Metal3ClusterList(a.(*Metal3ClusterList), b.(*v1alpha4.Metal3ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3ClusterList)(nil), (*Metal3ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3ClusterList_To_v1alpha2_Metal3ClusterList(a.(*v1alpha4.Metal3ClusterList), b.(*Metal3ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3Machine)(nil), (*v1alpha4.Metal3Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine(a.(*Metal3Machine), b.(*v1alpha4.Metal3Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3Machine)(nil), (*Metal3Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine(a.(*v1alpha4.Metal3Machine), b.(*Metal3Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineList)(nil), (*v1alpha4.Metal3MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineList_To_v1alpha4_Metal3MachineList(a.(*Metal3MachineList), b.(*v1alpha4.Metal3MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3MachineList)(nil), (*Metal3MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineList_To_v1alpha2_Metal3MachineList(a.(*v1alpha4.Metal3MachineList), b.(*Metal3MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineSpec)(nil), (*v1alpha4.Metal3MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(a.(*Metal3MachineSpec), b.(*v1alpha4.Metal3MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineTemplate)(nil), (*v1alpha4.Metal3MachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate(a.(*Metal3MachineTemplate), b.(*v1alpha4.Metal3MachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3MachineTemplate)(nil), (*Metal3MachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate(a.(*v1alpha4.Metal3MachineTemplate), b.(*Metal3MachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineTemplateList)(nil), (*v1alpha4.Metal3MachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineTemplateList_To_v1alpha4_Metal3MachineTemplateList(a.(*Metal3MachineTemplateList), b.(*v1alpha4.Metal3MachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3MachineTemplateList)(nil), (*Metal3MachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineTemplateList_To_v1alpha2_Metal3MachineTemplateList(a.(*v1alpha4.Metal3MachineTemplateList), b.(*Metal3MachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineTemplateResource)(nil), (*v1alpha4.Metal3MachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource(a.(*Metal3MachineTemplateResource), b.(*v1alpha4.Metal3MachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3MachineTemplateResource)(nil), (*Metal3MachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource(a.(*v1alpha4.Metal3MachineTemplateResource), b.(*Metal3MachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metal3MachineTemplateSpec)(nil), (*v1alpha4.Metal3MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec(a.(*Metal3MachineTemplateSpec), b.(*v1alpha4.Metal3MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Metal3MachineTemplateSpec)(nil), (*Metal3MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec(a.(*v1alpha4.Metal3MachineTemplateSpec), b.(*Metal3MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Metal3ClusterSpec)(nil), (*v1alpha4.Metal3ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3ClusterSpec_To_v1alpha4_Metal3ClusterSpec(a.(*Metal3ClusterSpec), b.(*v1alpha4.Metal3ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Metal3ClusterStatus)(nil), (*v1alpha4.Metal3ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3ClusterStatus_To_v1alpha4_Metal3ClusterStatus(a.(*Metal3ClusterStatus), b.(*v1alpha4.Metal3ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Metal3MachineStatus)(nil), (*v1alpha4.Metal3MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metal3MachineStatus_To_v1alpha4_Metal3MachineStatus(a.(*Metal3MachineStatus), b.(*v1alpha4.Metal3MachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.Metal3ClusterSpec)(nil), (*Metal3ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3ClusterSpec_To_v1alpha2_Metal3ClusterSpec(a.(*v1alpha4.Metal3ClusterSpec), b.(*Metal3ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.Metal3ClusterStatus)(nil), (*Metal3ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3ClusterStatus_To_v1alpha2_Metal3ClusterStatus(a.(*v1alpha4.Metal3ClusterStatus), b.(*Metal3ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.Metal3MachineSpec)(nil), (*Metal3MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineSpec_To_v1alpha2_Metal3MachineSpec(a.(*v1alpha4.Metal3MachineSpec), b.(*Metal3MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.Metal3MachineStatus)(nil), (*Metal3MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Metal3MachineStatus_To_v1alpha2_Metal3MachineStatus(a.(*v1alpha4.Metal3MachineStatus), b.(*Metal3MachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_APIEndpoint_To_v1alpha4_APIEndpoint(in *APIEndpoint, out *v1alpha4.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha2_APIEndpoint_To_v1alpha4_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha2_APIEndpoint_To_v1alpha4_APIEndpoint(in *APIEndpoint, out *v1alpha4.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha2_APIEndpoint_To_v1alpha4_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha4_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha4.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha4_APIEndpoint_To_v1alpha2_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha4_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha4.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha4_APIEndpoint_To_v1alpha2_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha2_HostSelector_To_v1alpha4_HostSelector(in *HostSelector, out *v1alpha4.HostSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]v1alpha4.HostSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha2_HostSelector_To_v1alpha4_HostSelector is an autogenerated conversion function.
func Convert_v1alpha2_HostSelector_To_v1alpha4_HostSelector(in *HostSelector, out *v1alpha4.HostSelector, s conversion.Scope) error {
	return autoConvert_v1alpha2_HostSelector_To_v1alpha4_HostSelector(in, out, s)
}

func autoConvert_v1alpha4_HostSelector_To_v1alpha2_HostSelector(in *v1alpha4.HostSelector, out *HostSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]HostSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha4_HostSelector_To_v1alpha2_HostSelector is an autogenerated conversion function.
func Convert_v1alpha4_HostSelector_To_v1alpha2_HostSelector(in *v1alpha4.HostSelector, out *HostSelector, s conversion.Scope) error {
	return autoConvert_v1alpha4_HostSelector_To_v1alpha2_HostSelector(in, out, s)
}

func autoConvert_v1alpha2_HostSelectorRequirement_To_v1alpha4_HostSelectorRequirement(in *HostSelectorRequirement, out *v1alpha4.HostSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = selection.Operator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha2_HostSelectorRequirement_To_v1alpha4_HostSelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha2_HostSelectorRequirement_To_v1alpha4_HostSelectorRequirement(in *HostSelectorRequirement, out *v1alpha4.HostSelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha2_HostSelectorRequirement_To_v1alpha4_HostSelectorRequirement(in, out, s)
}

func autoConvert_v1alpha4_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in *v1alpha4.HostSelectorRequirement, out *HostSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = selection.Operator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha4_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha4_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in *v1alpha4.HostSelectorRequirement, out *HostSelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha4_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in, out, s)
}

func autoConvert_v1alpha2_Image_To_v1alpha4_Image(in *Image, out *v1alpha4.Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	return nil
}

// Convert_v1alpha2_Image_To_v1alpha4_Image is an autogenerated conversion function.
func Convert_v1alpha2_Image_To_v1alpha4_Image(in *Image, out *v1alpha4.Image, s conversion.Scope) error {
	return autoConvert_v1alpha2_Image_To_v1alpha4_Image(in, out, s)
}

func autoConvert_v1alpha4_Image_To_v1alpha2_Image(in *v1alpha4.Image, out *Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	return nil
}

// Convert_v1alpha4_Image_To_v1alpha2_Image is an autogenerated conversion function.
func Convert_v1alpha4_Image_To_v1alpha2_Image(in *v1alpha4.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1alpha4_Image_To_v1alpha2_Image(in, out, s)
}

func autoConvert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster(in *Metal3Cluster, out *v1alpha4.Metal3Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_Metal3ClusterSpec_To_v1alpha4_Metal3ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_Metal3ClusterStatus_To_v1alpha4_Metal3ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster is an autogenerated conversion function.
func Convert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster(in *Metal3Cluster, out *v1alpha4.Metal3Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster(in, out, s)
}

func autoConvert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster(in *v1alpha4.Metal3Cluster, out *Metal3Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_Metal3ClusterSpec_To_v1alpha2_Metal3ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Metal3ClusterStatus_To_v1alpha2_Metal3ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster is an autogenerated conversion function.
func Convert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster(in *v1alpha4.Metal3Cluster, out *Metal3Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster(in, out, s)
}

func autoConvert_v1alpha2_Metal3ClusterList_To_v1alpha4_Metal3ClusterList(in *Metal3ClusterList, out *v1alpha4.Metal3ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.Metal3Cluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Metal3Cluster_To_v1alpha4_Metal3Cluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_Metal3ClusterList_To_v1alpha4_Metal3ClusterList is an autogenerated conversion function.
func Convert_v1alpha2_Metal3ClusterList_To_v1alpha4_Metal3ClusterList(in *Metal3ClusterList, out *v1alpha4.Metal3ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3ClusterList_To_v1alpha4_Metal3ClusterList(in, out, s)
}

func autoConvert_v1alpha4_Metal3ClusterList_To_v1alpha2_Metal3ClusterList(in *v1alpha4.Metal3ClusterList, out *Metal3ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Metal3Cluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_Metal3Cluster_To_v1alpha2_Metal3Cluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_Metal3ClusterList_To_v1alpha2_Metal3ClusterList is an autogenerated conversion function.
func Convert_v1alpha4_Metal3ClusterList_To_v1alpha2_Metal3ClusterList(in *v1alpha4.Metal3ClusterList, out *Metal3ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3ClusterList_To_v1alpha2_Metal3ClusterList(in, out, s)
}

func autoConvert_v1alpha2_Metal3ClusterSpec_To_v1alpha4_Metal3ClusterSpec(in *Metal3ClusterSpec, out *v1alpha4.Metal3ClusterSpec, s conversion.Scope) error {
	// WARNING: in.APIEndpoint requires manual conversion: does not exist in peer-type
	out.NoCloudProvider = in.NoCloudProvider
	return nil
}

func autoConvert_v1alpha4_Metal3ClusterSpec_To_v1alpha2_Metal3ClusterSpec(in *v1alpha4.Metal3ClusterSpec, out *Metal3ClusterSpec, s conversion.Scope) error {
	// WARNING: in.ControlPlaneEndpoint requires manual conversion: does not exist in peer-type
	out.NoCloudProvider = in.NoCloudProvider
	return nil
}

func autoConvert_v1alpha2_Metal3ClusterStatus_To_v1alpha4_Metal3ClusterStatus(in *Metal3ClusterStatus, out *v1alpha4.Metal3ClusterStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	out.Ready = in.Ready
	// WARNING: in.APIEndpoints requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha4_Metal3ClusterStatus_To_v1alpha2_Metal3ClusterStatus(in *v1alpha4.Metal3ClusterStatus, out *Metal3ClusterStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine(in *Metal3Machine, out *v1alpha4.Metal3Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_Metal3MachineStatus_To_v1alpha4_Metal3MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine is an autogenerated conversion function.
func Convert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine(in *Metal3Machine, out *v1alpha4.Metal3Machine, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine(in, out, s)
}

func autoConvert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine(in *v1alpha4.Metal3Machine, out *Metal3Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_Metal3MachineSpec_To_v1alpha2_Metal3MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_Metal3MachineStatus_To_v1alpha2_Metal3MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine is an autogenerated conversion function.
func Convert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine(in *v1alpha4.Metal3Machine, out *Metal3Machine, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine(in, out, s)
}

func autoConvert_v1alpha2_Metal3MachineList_To_v1alpha4_Metal3MachineList(in *Metal3MachineList, out *v1alpha4.Metal3MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.Metal3Machine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Metal3Machine_To_v1alpha4_Metal3Machine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineList_To_v1alpha4_Metal3MachineList is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineList_To_v1alpha4_Metal3MachineList(in *Metal3MachineList, out *v1alpha4.Metal3MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineList_To_v1alpha4_Metal3MachineList(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineList_To_v1alpha2_Metal3MachineList(in *v1alpha4.Metal3MachineList, out *Metal3MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Metal3Machine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_Metal3Machine_To_v1alpha2_Metal3Machine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_Metal3MachineList_To_v1alpha2_Metal3MachineList is an autogenerated conversion function.
func Convert_v1alpha4_Metal3MachineList_To_v1alpha2_Metal3MachineList(in *v1alpha4.Metal3MachineList, out *Metal3MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3MachineList_To_v1alpha2_Metal3MachineList(in, out, s)
}

func autoConvert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(in *Metal3MachineSpec, out *v1alpha4.Metal3MachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha2_Image_To_v1alpha4_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.UserData = (*corev1.SecretReference)(unsafe.Pointer(in.UserData))
	if err := Convert_v1alpha2_HostSelector_To_v1alpha4_HostSelector(&in.HostSelector, &out.HostSelector, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(in *Metal3MachineSpec, out *v1alpha4.Metal3MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineSpec_To_v1alpha2_Metal3MachineSpec(in *v1alpha4.Metal3MachineSpec, out *Metal3MachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha4_Image_To_v1alpha2_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.UserData = (*corev1.SecretReference)(unsafe.Pointer(in.UserData))
	if err := Convert_v1alpha4_HostSelector_To_v1alpha2_HostSelector(&in.HostSelector, &out.HostSelector, s); err != nil {
		return err
	}
	// WARNING: in.DataTemplate requires manual conversion: does not exist in peer-type
	// WARNING: in.MetaData requires manual conversion: does not exist in peer-type
	// WARNING: in.NetworkData requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_Metal3MachineStatus_To_v1alpha4_Metal3MachineStatus(in *Metal3MachineStatus, out *v1alpha4.Metal3MachineStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	out.Addresses = *(*v1alpha3.MachineAddresses)(unsafe.Pointer(&in.Addresses))
	out.Phase = in.Phase
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha4_Metal3MachineStatus_To_v1alpha2_Metal3MachineStatus(in *v1alpha4.Metal3MachineStatus, out *Metal3MachineStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.Addresses = *(*apiv1alpha2.MachineAddresses)(unsafe.Pointer(&in.Addresses))
	out.Phase = in.Phase
	out.Ready = in.Ready
	// WARNING: in.UserData requires manual conversion: does not exist in peer-type
	// WARNING: in.RenderedData requires manual conversion: does not exist in peer-type
	// WARNING: in.MetaData requires manual conversion: does not exist in peer-type
	// WARNING: in.NetworkData requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate(in *Metal3MachineTemplate, out *v1alpha4.Metal3MachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate(in *Metal3MachineTemplate, out *v1alpha4.Metal3MachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate(in *v1alpha4.Metal3MachineTemplate, out *Metal3MachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate(in *v1alpha4.Metal3MachineTemplate, out *Metal3MachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_Metal3MachineTemplateList_To_v1alpha4_Metal3MachineTemplateList(in *Metal3MachineTemplateList, out *v1alpha4.Metal3MachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.Metal3MachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Metal3MachineTemplate_To_v1alpha4_Metal3MachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineTemplateList_To_v1alpha4_Metal3MachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineTemplateList_To_v1alpha4_Metal3MachineTemplateList(in *Metal3MachineTemplateList, out *v1alpha4.Metal3MachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineTemplateList_To_v1alpha4_Metal3MachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineTemplateList_To_v1alpha2_Metal3MachineTemplateList(in *v1alpha4.Metal3MachineTemplateList, out *Metal3MachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Metal3MachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_Metal3MachineTemplate_To_v1alpha2_Metal3MachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_Metal3MachineTemplateList_To_v1alpha2_Metal3MachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_Metal3MachineTemplateList_To_v1alpha2_Metal3MachineTemplateList(in *v1alpha4.Metal3MachineTemplateList, out *Metal3MachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3MachineTemplateList_To_v1alpha2_Metal3MachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource(in *Metal3MachineTemplateResource, out *v1alpha4.Metal3MachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_Metal3MachineSpec_To_v1alpha4_Metal3MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource(in *Metal3MachineTemplateResource, out *v1alpha4.Metal3MachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource(in *v1alpha4.Metal3MachineTemplateResource, out *Metal3MachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_Metal3MachineSpec_To_v1alpha2_Metal3MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource(in *v1alpha4.Metal3MachineTemplateResource, out *Metal3MachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec(in *Metal3MachineTemplateSpec, out *v1alpha4.Metal3MachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_Metal3MachineTemplateResource_To_v1alpha4_Metal3MachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec(in *Metal3MachineTemplateSpec, out *v1alpha4.Metal3MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metal3MachineTemplateSpec_To_v1alpha4_Metal3MachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec(in *v1alpha4.Metal3MachineTemplateSpec, out *Metal3MachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_Metal3MachineTemplateResource_To_v1alpha2_Metal3MachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec(in *v1alpha4.Metal3MachineTemplateSpec, out *Metal3MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_Metal3MachineTemplateSpec_To_v1alpha2_Metal3MachineTemplateSpec(in, out, s)
}
