// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	v1alpha3 "github.com/metal3-io/cluster-api-provider-metal3/api/v1alpha3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	selection "k8s.io/apimachinery/pkg/selection"
	apiv1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*APIEndpoint), b.(*v1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(a.(*v1alpha3.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalCluster)(nil), (*v1alpha3.BareMetalCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster(a.(*BareMetalCluster), b.(*v1alpha3.BareMetalCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalCluster)(nil), (*BareMetalCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster(a.(*v1alpha3.BareMetalCluster), b.(*BareMetalCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalClusterList)(nil), (*v1alpha3.BareMetalClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalClusterList_To_v1alpha3_BareMetalClusterList(a.(*BareMetalClusterList), b.(*v1alpha3.BareMetalClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalClusterList)(nil), (*BareMetalClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalClusterList_To_v1alpha2_BareMetalClusterList(a.(*v1alpha3.BareMetalClusterList), b.(*BareMetalClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachine)(nil), (*v1alpha3.BareMetalMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine(a.(*BareMetalMachine), b.(*v1alpha3.BareMetalMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachine)(nil), (*BareMetalMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine(a.(*v1alpha3.BareMetalMachine), b.(*BareMetalMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineList)(nil), (*v1alpha3.BareMetalMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineList_To_v1alpha3_BareMetalMachineList(a.(*BareMetalMachineList), b.(*v1alpha3.BareMetalMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineList)(nil), (*BareMetalMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineList_To_v1alpha2_BareMetalMachineList(a.(*v1alpha3.BareMetalMachineList), b.(*BareMetalMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineSpec)(nil), (*v1alpha3.BareMetalMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(a.(*BareMetalMachineSpec), b.(*v1alpha3.BareMetalMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineSpec)(nil), (*BareMetalMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(a.(*v1alpha3.BareMetalMachineSpec), b.(*BareMetalMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineTemplate)(nil), (*v1alpha3.BareMetalMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineTemplate_To_v1alpha3_BareMetalMachineTemplate(a.(*BareMetalMachineTemplate), b.(*v1alpha3.BareMetalMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineTemplate)(nil), (*BareMetalMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineTemplate_To_v1alpha2_BareMetalMachineTemplate(a.(*v1alpha3.BareMetalMachineTemplate), b.(*BareMetalMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineTemplateList)(nil), (*v1alpha3.BareMetalMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineTemplateList_To_v1alpha3_BareMetalMachineTemplateList(a.(*BareMetalMachineTemplateList), b.(*v1alpha3.BareMetalMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineTemplateList)(nil), (*BareMetalMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineTemplateList_To_v1alpha2_BareMetalMachineTemplateList(a.(*v1alpha3.BareMetalMachineTemplateList), b.(*BareMetalMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineTemplateResource)(nil), (*v1alpha3.BareMetalMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource(a.(*BareMetalMachineTemplateResource), b.(*v1alpha3.BareMetalMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineTemplateResource)(nil), (*BareMetalMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource(a.(*v1alpha3.BareMetalMachineTemplateResource), b.(*BareMetalMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BareMetalMachineTemplateSpec)(nil), (*v1alpha3.BareMetalMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec(a.(*BareMetalMachineTemplateSpec), b.(*v1alpha3.BareMetalMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.BareMetalMachineTemplateSpec)(nil), (*BareMetalMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec(a.(*v1alpha3.BareMetalMachineTemplateSpec), b.(*BareMetalMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostSelector)(nil), (*v1alpha3.HostSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HostSelector_To_v1alpha3_HostSelector(a.(*HostSelector), b.(*v1alpha3.HostSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.HostSelector)(nil), (*HostSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_HostSelector_To_v1alpha2_HostSelector(a.(*v1alpha3.HostSelector), b.(*HostSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostSelectorRequirement)(nil), (*v1alpha3.HostSelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HostSelectorRequirement_To_v1alpha3_HostSelectorRequirement(a.(*HostSelectorRequirement), b.(*v1alpha3.HostSelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.HostSelectorRequirement)(nil), (*HostSelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(a.(*v1alpha3.HostSelectorRequirement), b.(*HostSelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*v1alpha3.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Image_To_v1alpha3_Image(a.(*Image), b.(*v1alpha3.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Image_To_v1alpha2_Image(a.(*v1alpha3.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BareMetalClusterSpec)(nil), (*v1alpha3.BareMetalClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalClusterSpec_To_v1alpha3_BareMetalClusterSpec(a.(*BareMetalClusterSpec), b.(*v1alpha3.BareMetalClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BareMetalClusterStatus)(nil), (*v1alpha3.BareMetalClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalClusterStatus_To_v1alpha3_BareMetalClusterStatus(a.(*BareMetalClusterStatus), b.(*v1alpha3.BareMetalClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BareMetalMachineStatus)(nil), (*v1alpha3.BareMetalMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BareMetalMachineStatus_To_v1alpha3_BareMetalMachineStatus(a.(*BareMetalMachineStatus), b.(*v1alpha3.BareMetalMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.BareMetalClusterSpec)(nil), (*BareMetalClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalClusterSpec_To_v1alpha2_BareMetalClusterSpec(a.(*v1alpha3.BareMetalClusterSpec), b.(*BareMetalClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.BareMetalClusterStatus)(nil), (*BareMetalClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalClusterStatus_To_v1alpha2_BareMetalClusterStatus(a.(*v1alpha3.BareMetalClusterStatus), b.(*BareMetalClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.BareMetalMachineStatus)(nil), (*BareMetalMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BareMetalMachineStatus_To_v1alpha2_BareMetalMachineStatus(a.(*v1alpha3.BareMetalMachineStatus), b.(*BareMetalMachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in *APIEndpoint, out *v1alpha3.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in *APIEndpoint, out *v1alpha3.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha3.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha3.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster(in *BareMetalCluster, out *v1alpha3.BareMetalCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_BareMetalClusterSpec_To_v1alpha3_BareMetalClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_BareMetalClusterStatus_To_v1alpha3_BareMetalClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster(in *BareMetalCluster, out *v1alpha3.BareMetalCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster(in, out, s)
}

func autoConvert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster(in *v1alpha3.BareMetalCluster, out *BareMetalCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_BareMetalClusterSpec_To_v1alpha2_BareMetalClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_BareMetalClusterStatus_To_v1alpha2_BareMetalClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster(in *v1alpha3.BareMetalCluster, out *BareMetalCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster(in, out, s)
}

func autoConvert_v1alpha2_BareMetalClusterList_To_v1alpha3_BareMetalClusterList(in *BareMetalClusterList, out *v1alpha3.BareMetalClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.BareMetalCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_BareMetalCluster_To_v1alpha3_BareMetalCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_BareMetalClusterList_To_v1alpha3_BareMetalClusterList is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalClusterList_To_v1alpha3_BareMetalClusterList(in *BareMetalClusterList, out *v1alpha3.BareMetalClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalClusterList_To_v1alpha3_BareMetalClusterList(in, out, s)
}

func autoConvert_v1alpha3_BareMetalClusterList_To_v1alpha2_BareMetalClusterList(in *v1alpha3.BareMetalClusterList, out *BareMetalClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_BareMetalCluster_To_v1alpha2_BareMetalCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_BareMetalClusterList_To_v1alpha2_BareMetalClusterList is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalClusterList_To_v1alpha2_BareMetalClusterList(in *v1alpha3.BareMetalClusterList, out *BareMetalClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalClusterList_To_v1alpha2_BareMetalClusterList(in, out, s)
}

func autoConvert_v1alpha2_BareMetalClusterSpec_To_v1alpha3_BareMetalClusterSpec(in *BareMetalClusterSpec, out *v1alpha3.BareMetalClusterSpec, s conversion.Scope) error {
	// WARNING: in.APIEndpoint requires manual conversion: does not exist in peer-type
	out.NoCloudProvider = in.NoCloudProvider
	return nil
}

func autoConvert_v1alpha3_BareMetalClusterSpec_To_v1alpha2_BareMetalClusterSpec(in *v1alpha3.BareMetalClusterSpec, out *BareMetalClusterSpec, s conversion.Scope) error {
	// WARNING: in.ControlPlaneEndpoint requires manual conversion: does not exist in peer-type
	out.NoCloudProvider = in.NoCloudProvider
	return nil
}

func autoConvert_v1alpha2_BareMetalClusterStatus_To_v1alpha3_BareMetalClusterStatus(in *BareMetalClusterStatus, out *v1alpha3.BareMetalClusterStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	out.Ready = in.Ready
	// WARNING: in.APIEndpoints requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_BareMetalClusterStatus_To_v1alpha2_BareMetalClusterStatus(in *v1alpha3.BareMetalClusterStatus, out *BareMetalClusterStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine(in *BareMetalMachine, out *v1alpha3.BareMetalMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_BareMetalMachineStatus_To_v1alpha3_BareMetalMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine(in *BareMetalMachine, out *v1alpha3.BareMetalMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine(in *v1alpha3.BareMetalMachine, out *BareMetalMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_BareMetalMachineStatus_To_v1alpha2_BareMetalMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine(in *v1alpha3.BareMetalMachine, out *BareMetalMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineList_To_v1alpha3_BareMetalMachineList(in *BareMetalMachineList, out *v1alpha3.BareMetalMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.BareMetalMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_BareMetalMachine_To_v1alpha3_BareMetalMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachineList_To_v1alpha3_BareMetalMachineList is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineList_To_v1alpha3_BareMetalMachineList(in *BareMetalMachineList, out *v1alpha3.BareMetalMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineList_To_v1alpha3_BareMetalMachineList(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineList_To_v1alpha2_BareMetalMachineList(in *v1alpha3.BareMetalMachineList, out *BareMetalMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_BareMetalMachine_To_v1alpha2_BareMetalMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachineList_To_v1alpha2_BareMetalMachineList is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineList_To_v1alpha2_BareMetalMachineList(in *v1alpha3.BareMetalMachineList, out *BareMetalMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineList_To_v1alpha2_BareMetalMachineList(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(in *BareMetalMachineSpec, out *v1alpha3.BareMetalMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha2_Image_To_v1alpha3_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.UserData = (*corev1.SecretReference)(unsafe.Pointer(in.UserData))
	if err := Convert_v1alpha2_HostSelector_To_v1alpha3_HostSelector(&in.HostSelector, &out.HostSelector, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(in *BareMetalMachineSpec, out *v1alpha3.BareMetalMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(in *v1alpha3.BareMetalMachineSpec, out *BareMetalMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha3_Image_To_v1alpha2_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.UserData = (*corev1.SecretReference)(unsafe.Pointer(in.UserData))
	if err := Convert_v1alpha3_HostSelector_To_v1alpha2_HostSelector(&in.HostSelector, &out.HostSelector, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(in *v1alpha3.BareMetalMachineSpec, out *BareMetalMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineStatus_To_v1alpha3_BareMetalMachineStatus(in *BareMetalMachineStatus, out *v1alpha3.BareMetalMachineStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	out.Addresses = *(*apiv1alpha3.MachineAddresses)(unsafe.Pointer(&in.Addresses))
	out.Phase = in.Phase
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha3_BareMetalMachineStatus_To_v1alpha2_BareMetalMachineStatus(in *v1alpha3.BareMetalMachineStatus, out *BareMetalMachineStatus, s conversion.Scope) error {
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.Addresses = *(*apiv1alpha2.MachineAddresses)(unsafe.Pointer(&in.Addresses))
	out.Phase = in.Phase
	out.Ready = in.Ready
	return nil
}

func autoConvert_v1alpha2_BareMetalMachineTemplate_To_v1alpha3_BareMetalMachineTemplate(in *BareMetalMachineTemplate, out *v1alpha3.BareMetalMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachineTemplate_To_v1alpha3_BareMetalMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineTemplate_To_v1alpha3_BareMetalMachineTemplate(in *BareMetalMachineTemplate, out *v1alpha3.BareMetalMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineTemplate_To_v1alpha3_BareMetalMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineTemplate_To_v1alpha2_BareMetalMachineTemplate(in *v1alpha3.BareMetalMachineTemplate, out *BareMetalMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachineTemplate_To_v1alpha2_BareMetalMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineTemplate_To_v1alpha2_BareMetalMachineTemplate(in *v1alpha3.BareMetalMachineTemplate, out *BareMetalMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineTemplate_To_v1alpha2_BareMetalMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineTemplateList_To_v1alpha3_BareMetalMachineTemplateList(in *BareMetalMachineTemplateList, out *v1alpha3.BareMetalMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha3.BareMetalMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_BareMetalMachineTemplateList_To_v1alpha3_BareMetalMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineTemplateList_To_v1alpha3_BareMetalMachineTemplateList(in *BareMetalMachineTemplateList, out *v1alpha3.BareMetalMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineTemplateList_To_v1alpha3_BareMetalMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineTemplateList_To_v1alpha2_BareMetalMachineTemplateList(in *v1alpha3.BareMetalMachineTemplateList, out *BareMetalMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BareMetalMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_BareMetalMachineTemplateList_To_v1alpha2_BareMetalMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineTemplateList_To_v1alpha2_BareMetalMachineTemplateList(in *v1alpha3.BareMetalMachineTemplateList, out *BareMetalMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineTemplateList_To_v1alpha2_BareMetalMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource(in *BareMetalMachineTemplateResource, out *v1alpha3.BareMetalMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_BareMetalMachineSpec_To_v1alpha3_BareMetalMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource(in *BareMetalMachineTemplateResource, out *v1alpha3.BareMetalMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource(in *v1alpha3.BareMetalMachineTemplateResource, out *BareMetalMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_BareMetalMachineSpec_To_v1alpha2_BareMetalMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource(in *v1alpha3.BareMetalMachineTemplateResource, out *BareMetalMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec(in *BareMetalMachineTemplateSpec, out *v1alpha3.BareMetalMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_BareMetalMachineTemplateResource_To_v1alpha3_BareMetalMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec(in *BareMetalMachineTemplateSpec, out *v1alpha3.BareMetalMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_BareMetalMachineTemplateSpec_To_v1alpha3_BareMetalMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec(in *v1alpha3.BareMetalMachineTemplateSpec, out *BareMetalMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_BareMetalMachineTemplateResource_To_v1alpha2_BareMetalMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec(in *v1alpha3.BareMetalMachineTemplateSpec, out *BareMetalMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_BareMetalMachineTemplateSpec_To_v1alpha2_BareMetalMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_HostSelector_To_v1alpha3_HostSelector(in *HostSelector, out *v1alpha3.HostSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]v1alpha3.HostSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha2_HostSelector_To_v1alpha3_HostSelector is an autogenerated conversion function.
func Convert_v1alpha2_HostSelector_To_v1alpha3_HostSelector(in *HostSelector, out *v1alpha3.HostSelector, s conversion.Scope) error {
	return autoConvert_v1alpha2_HostSelector_To_v1alpha3_HostSelector(in, out, s)
}

func autoConvert_v1alpha3_HostSelector_To_v1alpha2_HostSelector(in *v1alpha3.HostSelector, out *HostSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]HostSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha3_HostSelector_To_v1alpha2_HostSelector is an autogenerated conversion function.
func Convert_v1alpha3_HostSelector_To_v1alpha2_HostSelector(in *v1alpha3.HostSelector, out *HostSelector, s conversion.Scope) error {
	return autoConvert_v1alpha3_HostSelector_To_v1alpha2_HostSelector(in, out, s)
}

func autoConvert_v1alpha2_HostSelectorRequirement_To_v1alpha3_HostSelectorRequirement(in *HostSelectorRequirement, out *v1alpha3.HostSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = selection.Operator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha2_HostSelectorRequirement_To_v1alpha3_HostSelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha2_HostSelectorRequirement_To_v1alpha3_HostSelectorRequirement(in *HostSelectorRequirement, out *v1alpha3.HostSelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha2_HostSelectorRequirement_To_v1alpha3_HostSelectorRequirement(in, out, s)
}

func autoConvert_v1alpha3_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in *v1alpha3.HostSelectorRequirement, out *HostSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = selection.Operator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha3_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha3_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in *v1alpha3.HostSelectorRequirement, out *HostSelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha3_HostSelectorRequirement_To_v1alpha2_HostSelectorRequirement(in, out, s)
}

func autoConvert_v1alpha2_Image_To_v1alpha3_Image(in *Image, out *v1alpha3.Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	return nil
}

// Convert_v1alpha2_Image_To_v1alpha3_Image is an autogenerated conversion function.
func Convert_v1alpha2_Image_To_v1alpha3_Image(in *Image, out *v1alpha3.Image, s conversion.Scope) error {
	return autoConvert_v1alpha2_Image_To_v1alpha3_Image(in, out, s)
}

func autoConvert_v1alpha3_Image_To_v1alpha2_Image(in *v1alpha3.Image, out *Image, s conversion.Scope) error {
	out.URL = in.URL
	out.Checksum = in.Checksum
	return nil
}

// Convert_v1alpha3_Image_To_v1alpha2_Image is an autogenerated conversion function.
func Convert_v1alpha3_Image_To_v1alpha2_Image(in *v1alpha3.Image, out *Image, s conversion.Scope) error {
	return autoConvert_v1alpha3_Image_To_v1alpha2_Image(in, out, s)
}
