on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

name: release

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    name: tag release
    # This workflow is only of value to the metal3-io/cluster-api-provider-metal3 repository and
    # would always fail in forks
    if: github.repository == 'metal3-io/cluster-api-provider-metal3'
    runs-on: ubuntu-latest
    steps:
      - name: Export RELEASE_TAG var
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'
      - name: Generate release artifacts and notes
        run: |
          make release
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          files: out/*
          body_path: releasenotes/${{ env.RELEASE_TAG }}.md
